# DSC200 Lecture 7 

## An introduction to NumPy

## NumPy

NumPy provides an efficient representation of multidimensional datasets like vectors and matricies, and tools for linear algebra and general matrix manipulations - essential building blocks of virtually all technical computing

Typically NumPy is imported as `np`:

In [18]:
import numpy as np

NumPy, at its core, provides a powerful array object.  Let's start by exploring how the NumPy array differs from a Python list.  

We start by creating a simple Python list and a NumPy array with identical contents:

In [19]:
lst = [10, 20, 30, 40]
arr = np.array([10, 20, 30, 40])
print(lst)
print(arr)

[10, 20, 30, 40]
[10 20 30 40]


### Element indexing

Elements of a one-dimensional array are accessed with the same syntax as a list:

In [20]:
print(lst[0], arr[0])

10 10


In [21]:
print(lst[-1], arr[-1])

40 40


In [22]:
print(lst[2:], arr[2:])

[30, 40] [30 40]


### Differences between arrays and lists

The first difference to note between lists and arrays is that arrays are *homogeneous*; i.e. all elements of an array must be of the same type.  In contrast, lists can contain elements of arbitrary type. For example, we can change the last element in our list above to be a string:

In [23]:
lst[-1] = 'a string inside a list'
lst

[10, 20, 30, 'a string inside a list']

But the same can not be done with an array, as we get an error message:

In [24]:
arr[-1] = 'a string inside an array'

ValueError: invalid literal for int() with base 10: 'a string inside an array'

Caveat, it can be done, but really *don't do it*; lists are generally better at non-homogeneous collections.

## Array Properties and Methods

The following provide basic information about the size, shape and data in the array:

In [25]:
print('Data type                :', arr.dtype)
print('Total number of elements :', arr.size)
print('Number of dimensions     :', arr.ndim)
print('Shape (dimensionality)   :', arr.shape)
print('Memory used (in bytes)   :', arr.nbytes)

Data type                : int32
Total number of elements : 4
Number of dimensions     : 1
Shape (dimensionality)   : (4,)
Memory used (in bytes)   : 16


Arrays also have many useful statistical/mathematical methods:

In [26]:
print('Minimum and maximum             :', arr.min(), arr.max())
print('Sum and product of all elements :', arr.sum(), arr.prod())
print('Mean and standard deviation     :', arr.mean(), arr.std())

Minimum and maximum             : 10 40
Sum and product of all elements : 100 240000
Mean and standard deviation     : 25.0 11.180339887498949


### Data types

The information about the type of an array is contained in its `dtype` attribute.

In [27]:
arr.dtype

dtype('int32')

Once an array has been created, its `dtype` is fixed (in this case to an 8 byte/64 bit signed integer) and it can only store elements of the same type.

For this example where the `dtype` is integer, if we try storing a floating point number in the array it will be automatically converted into an integer:

In [28]:
arr[-1] = 1.234
arr

array([10, 20, 30,  1])

NumPy comes with most of the common data types (and some uncommon ones too).

The most used (and portable) dtypes are:

* bool
* uint8
* int (machine dependent)
* int8
* int32
* int64
* float (machine dependent)
* float32
* float64

Full details can be found at http://docs.scipy.org/doc/numpy/user/basics.types.html.

What are the limits of the common NumPy integer types?

In [29]:
np.array(256, dtype=np.uint8)

C:\Users\peng yao\AppData\Local\Temp\ipykernel_41796\257501797.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array(256, dtype=np.uint8)


array(0, dtype=uint8)

In [30]:
float_info = ('{finfo.dtype}: max={finfo.max:<18}, '
              'approx decimal precision={finfo.precision};')
print(float_info.format(finfo=np.finfo(np.float32)))
print(float_info.format(finfo=np.finfo(np.float64)))

float32: max=3.4028234663852886e+38, approx decimal precision=6;
float64: max=1.7976931348623157e+308, approx decimal precision=15;


## Pop quiz

What is the output of the below code:

In [31]:
np.array(128, dtype=np.int8)

C:\Users\peng yao\AppData\Local\Temp\ipykernel_41796\294131257.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array(128, dtype=np.int8)


array(-128, dtype=int8)

<table border="1" class="docutils">
<colgroup>
<col width="14%" />
<col width="86%" />
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head"></th>
<th class="head">Number of matches</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><tt class="docutils literal"><span class="pre">A</span></tt></td>
<td>-128</td>
</tr>
<tr class="row-odd"><td><tt class="docutils literal"><span class="pre">B</span></tt></td>
<td>-127</td>
</tr>
<tr class="row-even"><td><tt class="docutils literal"><span class="pre">C</span></tt></td>
<td>0</td>
</tr>
<tr class="row-odd"><td><tt class="docutils literal"><span class="pre">D</span></tt></td>
<td>128</td>
</tr>
<tr class="row-even"><td><tt class="docutils literal"><span class="pre">E</span></tt></td>
<td>An error</td>
</tr>
</tbody>
</table>

Floating point precision is covered in detail at http://en.wikipedia.org/wiki/Floating_point.

However, we can convert an array from one type to another with the ``astype`` method

In [32]:
np.array(1, dtype=np.uint8).astype(np.float32)

array(1., dtype=float32)

## Creating Arrays

Above we created an array from an existing list. Now let's look into other ways in which we can create arrays.

A common need is to have an array initialized with a constant value. Very often this value is 0 or 1.

`zeros` creates arrays of all zeros, with any desired dtype:

In [33]:
np.zeros(5, dtype=np.float64)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros(3, dtype=np.int32)

array([0, 0, 0])

and similarly for `ones`:

In [35]:
print('5 ones:', np.ones(5, dtype=np.int32))

5 ones: [1 1 1 1 1]


If we want an array initialized with an arbitrary value, we can create an empty array and then use the fill method to put the value we want into the array:

In [36]:
a = np.empty(4, dtype=np.float32)
a.fill(5.5)
a

array([5.5, 5.5, 5.5, 5.5], dtype=float32)

Alternatives, such as:

 * ``np.ones(4) * 5.5``
 * ``np.zeros(4) + 5.5``

are generally less efficient, but are also reasonable.

### Filling arrays with sequences

NumPy also offers the `arange` function, which works like the builtin `range` but returns an array instead of a list:

In [37]:
np.arange(10, dtype=np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
np.arange(5, 7, 0.1)

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2,
       6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9])

In [59]:
A = np.arange(1,9).reshape(2,4)
print(A)
B = np.array([1, 2])
print(B)
B = B.reshape(2, 1)
print(A + B)

C = A + B
C[C > 5]

[[1 2 3 4]
 [5 6 7 8]]
[1 2]
[[ 2  3  4  5]
 [ 7  8  9 10]]


array([ 7,  8,  9, 10])

The `linspace` and `logspace` functions to create linearly and logarithmically-spaced grids respectively, with a fixed number of points that include both ends of the specified interval:

In [41]:
print("A linear grid between 0 and 1:")
print(np.linspace(0, 1, 5))

A linear grid between 0 and 1:
[0.   0.25 0.5  0.75 1.  ]


In [42]:
print("A logarithmic grid between 10**2 and 10**4:")
print(np.logspace(2, 4, 3))

A logarithmic grid between 10**2 and 10**4:
[  100.  1000. 10000.]


### Creating random arrays

Finally, it is often useful to create arrays with random numbers that follow a specific distribution.  The `np.random` module contains a number of functions that can be used to this effect.
First, we must import it:

In [43]:
import numpy as np
import numpy.random

To produce an array of 5 random samples taken from a standard normal distribution (0 mean and variance 1):

In [44]:
print(np.random.randn(5))

[-1.13303723  0.7933726   0.67706028 -0.70811208 -1.56163926]


For an array of 5 samples from the normal distribution with a mean of 10 and a variance of 3:

In [62]:
# 生成符合正态分布（高斯分布）的随机数
# mean - 均值
# variance - 方差（分散程度）

norm10 = np.random.normal(10, 3, 5)
print(norm10)

[ 9.09155385 10.9172952   7.82677783  9.75237877  8.24229811]


In [46]:
# 生成一个在指定范围内的随机整数

np.random.randint(5, 11) # [5,11) / [5,10]

7

In [47]:
# 从指定范围内随机选择一个元素

np.random.choice(range(5, 11))

8

## Indexing with other arrays

Above we saw how to index NumPy arrays with single numbers and slices, just like Python lists.  

Arrays also allow for a more sophisticated kind of indexing that is very powerful: you can index an array with another array, and in particular with an array of boolean values.  

This is particularly useful to extract information from an array that matches a certain condition.

Consider for example that in the array `norm10` we want to replace all values above 9 with the value 0.  We can do so by first finding the *mask* that indicates where this condition is true or false:

In [63]:
mask = norm10 > 9
mask

array([ True,  True, False,  True, False])

In [64]:
nanarray=np.array([-1., 0., 1., np.NaN])

In [65]:
nanarray > 0.5

array([False, False,  True, False])

In [66]:
nanarray <= 0.5

array([ True,  True, False, False])

In [53]:
# np.isnan 函数用于检查数组中的元素是否为 NaN（Not a Number）

nanarray[~np.isnan(nanarray)] > 0.5

array([False, False,  True])

Now that we have this mask, we can use it to either read those values or to reset them to 0:

In [67]:
print(('Values above 9:', norm10[mask]))

('Values above 9:', array([ 9.09155385, 10.9172952 ,  9.75237877]))


In [68]:
print('Resetting all values above 9 to 0...')
norm10[mask] = 0
print(norm10)

Resetting all values above 9 to 0...
[0.         0.         7.82677783 0.         8.24229811]


Whilst beyond the scope of this course, it is also worth knowing that a specific masked array object exists in NumPy.
Further details are available at http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html

## Arrays with more than one dimension

Up until now all our examples have used one-dimensional arrays.  NumPy can also create arrays of arbitrary dimensions, and all the methods illustrated in the previous section work on arrays with more than one dimension.

A list of lists can be used to initialize a two dimensional array:

In [69]:
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


With two-dimensional arrays we start seeing the power of NumPy: while nested lists can be indexed by repeatedly using the `[ ]` operator, multidimensional arrays support a much more natural indexing syntax using a single `[ ]` and a set of indices separated by commas:

In [57]:
print(lst2[0][1])
print(arr2[0, 1])

2
2


Question: Why does the following example produce different results?

In [70]:
# lst2[0:2][1]
# lst2[0:2] - 取 lst2 列表的前两个元素（下标为 0 和 1 的元素），这会生成一个新的列表
# lst2[0:2][1] - 从上一步提取的列表中提取索引 1 的元素

# arr2[:, 1]：从 arr2 中提取所有行的第二列（索引为 1 的列）

print(lst2[0:2][1])
print(arr2[:, 1])

[4, 5, 6]
[2 5]
